### ISSUE TITLE
No metrics exported using otel-stream-handler, while otel-handler does

### ISSUE THREAD

**Issue by sge93** [open-telemetry/opentelemetry-lambda-extension#1051]
**Describe the bug**
I am using the java wrapper for an AWS Lambda to export metrics to Amazon Managed Prometheus. The Lambda is setup with Spring Cloud Functions in a declarative way with the handler:
`org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest` 
which is implementing the AWS Lambda RequestStreamHandler. 

When I invoke the Lambda through an S3 Event, it starts and processes it without any problems and the handler seems to be correct as I have the wrapper set to **otel-stream-handler**:
`[ main] o.s.c.f.a.aws.CustomRuntimeInitializer : AWS Handler: io.opentelemetry.instrumentation.awslambdacore.v1_0.TracingRequestStreamWrapper`

Unfortunately no metrics are exported to AMP. I have this Bean where I add a counter for the sake of testing:
```
@Bean
    Meter meter() {
        var meter = GlobalOpenTelemetry.getMeterProvider().meterBuilder("aws-otel").setInstrumentationVersion("1.0").build(); 
        var test = meter.counterBuilder("test1").setDescription("test").build(); 
        test.add(1234); 
        return meter; 
    }
```

When I set the AWS_LAMBDA_EXEC_WRAPPER to **/opt/otel-handler**  this counter is exported but the function cannot be processed as the otel-handler implementation does not support an `InputStream` which is expected. Still the metric defined in the Bean is exported to AMP and accessible via PromQL query. 

**Steps to reproduce**

- Spring Cloud Function with S3 Event Input deployed as AWS Lambda.

- Specify layer as:
`arn:aws:lambda:eu-central-1:901920570463:layer:aws-otel-java-wrapper-amd64-ver-1-31-0:1`

- Lambda Handler
`org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest`

```
    @Bean
    public Function<S3Event, String> function() {
       return event -> "OK";
   }
```

- Collector config:
```
# collector.yaml
extensions:
  sigv4auth:
    service: "aps" 
    region: <workspace_region>

receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  prometheusremotewrite:
    endpoint: <workspace_remote_write_url>
    auth: 
      authenticator: sigv4auth

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
```

- Use opentelemetry-api to export counter metrics.
- Lambda timeout is **120 seconds** and used **RAM is 1024MB**.

**What did you expect to see?**
I would expect to at least see the metrics defined in the Meter bean as the dependency is required in further processing components (which runs through successfully) and therefore should be available in the ApplicationContext. Prometheus workspace queries show no results.

**What did you see instead?**
No logs indicating a failure. At some point minutes later the logs show:
`{"level":"info","ts":1702461394.1761792,"logger":"lifecycle.manager","msg":"Received SHUTDOWN event"}`

**What version of collector/language SDK version did you use?**
- OpenTelemetry Lambda extension v0.35.0
- arn:aws:lambda:eu-central-1:901920570463:layer:aws-otel-java-wrapper-amd64-ver-1-31-0:1
- io.opentelemetry:opentelemetry-bom:1.32.0
- Java 17
- org.springframework.cloud:spring-cloud-function-dependencies:4.1.0

**What language layer did you use?**
- Java
