### ISSUE TITLE
NodeJS Collector: connect ECONNREFUSED 127.0.0.1:4318

### ISSUE THREAD

**Issue by hampusrosvall** [open-telemetry/opentelemetry-lambda-extension#1218]
**Describe the bug**
I am using the NodeJS Lambda layer and I am seeing the following error in the logs upon each invocation. I am not sure if this is a bug, or if I am doing something wrong. Appreciate the help regardless!

```json
{
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:4318\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)",
  "message": "connect ECONNREFUSED 127.0.0.1:4318",
  "errno": "-111",
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": "4318",
  "name": "Error"
}
``` 

**Steps to reproduce**
I am including the layer in my SAM `template.yml`

```yaml
EventProducer:
    Properties:
      ...
      Layers:
        - arn:aws:lambda:eu-west-1:184161586896:layer:opentelemetry-nodejs-0_5_0:1
```

exporting the following environment variables

```
OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
OTLP_EXPORTER_OTLP_ENDPOINT: 'http://ENDPOINT:PORT'
```

In my handler I am acquiring a Tracer using the following code and generating a span

```JavaScript
const tracer = trace.getTracer('EventProducer', '1.0');

function createPayload(traceEvent: Event, itemLoadedEvent: Event): Promise<Input> {
  return tracer.startActiveSpan('EventProducer.createPayload', async (span: Span) => {
    // do smth
    span.end();
    return payload;
  });
}
```
**What did you expect to see?**
I expect to see a trace signal exported to Collector

**What did you see instead?**
Error above

**What version of collector/language SDK version did you use?**
NodeSDK: "@opentelemetry/sdk-node": "^0.49.1",

**What language layer did you use?**
Config: arn:aws:lambda:eu-west-1:184161586896:layer:opentelemetry-nodejs-0_5_0:1

**Additional context**
`collector.yaml` config
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'

exporters:
  otlp:
    endpoint: 'ENDPOINT:PORT'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```
