### ISSUE TITLE
Otel Collector does not support metric receiver although docs advertise that it does.

### ISSUE THREAD

**Issue by bhaskarbanerjee** [open-telemetry/opentelemetry-lambda-extension#1425]
**Describe the bug**
OTel Lambda Collector [docs](https://github.com/solarwinds/opentelemetry-lambda/tree/feature/telemetryapireceiver-configuration/collector#opentelemetry-collector-aws-lambda-extension-layer) say that the collector extension _allows lambdas to use the OpenTelemetry Collector Exporter to send_ **traces and metrics** _to any configured backend_ while Telemetry API Receiver document [says](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/collector/receiver/telemetryapireceiver#telemetry-api-receiver).

The receiver is configured only for traces as seen [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/receiver/telemetryapireceiver/receiver.go#L48)

Is this a **miss** or **intentional**? And why is it advertised like it is, if this is intentional.

I do see a [PR](https://github.com/open-telemetry/opentelemetry-lambda/pull/1347) in progress to add support for Logs

**Steps to reproduce**
Added python proto layer. Added otel collector layer. There is manual instrumentation of custom metrics from the lambda code.
config.yaml looks like:
```
receivers:
  otlp:
    protocols:
      http:
 
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: enterprise.otelcollector.gateway.com
 
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 2s
```

**What did you expect to see?**
Per the documentation, we expected it to work for both traces and metrics (custom metrics)

**What did you see instead?**
Only traces were exported and collector threw clear error on endpoint /v1/metrics saying it has reached max number of retries.

**What version of collector SDK version did you use?**
[Version](https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-collector%2F0.8.0)

**What language layer did you use?**
Python

**Additional context**
No
