### ISSUE TITLE
Unable to get logs shipped from lambda to Loki

### ISSUE THREAD

**Issue by gkaskonas** [open-telemetry/opentelemetry-lambda-extension#1600]
**Describe the bug**
I am unable to get logs to ship using opentelemetry. I tried [pino http transport](https://github.com/pinojs/pino-opentelemetry-transport) but with no avail. 
Is there a way to configure opentelemetry to scrape stdout or lambda telemetry API?

**Steps to reproduce**
Configure a lambda with the instrumentation and collector layer. Log something in the lambda

**What did you expect to see?**
Logs in Loki.

**What did you see instead?**
Nothing. No errors either.

**What version of collector/language SDK version did you use?**
Instrumentation layer 0.11
Collector 0.12

**What language layer did you use?**
NodeJS

**Additional context**
Collector config:

```
receivers:
  otlp:
    protocols:
      http: 
  telemetryapi:
exporters:
  otlphttp:
    endpoint: 'https://tracing.internal.tools.company.io/otlp'
  otlphttp/logs:
    endpoint: 'https://loki.tools.company.io/otlp'
  prometheusremotewrite:
    endpoint: 'https://mimir.internal.tools.company.io/api/v1/push'
    resource_to_telemetry_conversion:
      enabled: true
    external_labels:
      source: aws-lambda
    remote_write_queue:
      enabled: true
      queue_size: 100000
      num_consumers: 50
  logging:

processors:
  coldstart:
  decouple:
  batch:
    timeout: 1m

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - telemetryapi
      exporters:
        - otlphttp
      processors:
        - batch
        - decouple
        - coldstart
    metrics:
      receivers:
        - otlp
      exporters:
        - prometheusremotewrite
      processors:
        - batch
        - decouple
    logs:
      receivers:
        - otlp
        - telemetryapi
      exporters:
        - otlphttp/logs
      processors:
        - batch
        - decouple
```

I am getting lambda telemetry metadata in loki. Like faas.name and faas.max_memory hwever, the log line itself is empty. Is my collector config OK? 
What am I doing wrong with application logs?
