### ISSUE TITLE
AWS lambda layer crashing on init

### ISSUE THREAD

**Issue by davidkeaveny** [open-telemetry/opentelemetry-lambda-extension#1651]
**Describe the bug**

I have a .NET 8 AWS Lambda function, to which I am attempting to add OpenTelemetry (publishing to New Relic). When I deploy and test the lambda, CloudWatch reports an extension initialisation error due to a misconfiguration.

**Steps to reproduce**

My `collector.yaml` is as follows, basically copy/pasted from the [New Relic documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet/):

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
```

My `template.yaml` applies the appropriate environment variables to configure it (using Octopus Deploy to set the API key at deploy time):

```
AWSTemplateFormatVersion: 2010-09-09

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  SaffGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: #{Octopus.Action[Deploy to S3].Output.Package.S3Uri}
      Handler: MyApplication::MyApplication.MyProject.Function::OpenTelemetryFunctionHandler
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 600
      Description: My Test Function
      Environment:
        Variables:
          DOTNET_ENVIRONMENT: Development
          NEW_RELIC_OPENTELEMETRY_ENDPOINT: otlp.nr-data.net:4317
          NEW_RELIC_LICENSE_KEY: #{NewRelic.LicenseKey}
          OTEL_SERVICE_NAME: my-project
          OPENTELEMETRY_COLLECTOR_CONFIG_URI: /var/task/collector.yaml
      Role: #{Aws.DoStuff.Role}
      Layers:
        - !Sub arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-collector-amd64-ver-0-115-0:2
      VpcConfig:
        SecurityGroupIds:
          - #{Aws.SecurityGroup}
        SubnetIds:
          - #{Aws.SubnetId}
          - #{Aws.SubnetId2}
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DoStuffGenerationFunction}"
      RetentionInDays: 7

Outputs:
  DoStuffGenerationFunction:
    Description: My Test Function ARN
    Value: !GetAtt DoStuffGenerationFunction.Arn
```

**What did you expect to see?**

I expected to see traces appearing in the New Relic dashboard.

**What did you see instead?**

No traces appear in the dashboard; instead, I see fatal errors in CloudWatch from the OTel lambda layer.

```
INIT_START Runtime Version: dotnet:8.v29 Runtime Version ARN: arn:aws:lambda:ap-southeast-2::runtime:a80f5bd0010789587efde8cc8718de53e230fba733dc31ed8ba53bf0d0b8d6f0
{"level":"info","ts":1736316461.5401077,"msg":"Launching OpenTelemetry Lambda extension","version":"v0.115.0"}
{"level":"info","ts":1736316461.5554593,"logger":"telemetryAPI.Listener","msg":"Listening for requests","address":"sandbox.localdomain:53612"}
{"level":"info","ts":1736316461.5583487,"logger":"telemetryAPI.Client","msg":"Subscribing","baseURL":"http://127.0.0.1:9001/2022-07-01/telemetry"}
TELEMETRY Name: collector State: Subscribed Types: [Platform]
{"level":"info","ts":1736316461.5643628,"logger":"telemetryAPI.Client","msg":"Subscription success","response":"\"OK\""}
{"level":"info","ts":1736316461.5644276,"logger":"NewCollector","msg":"Using config URI from environment variable","uri":"/var/task/collector.yaml"}
{"level":"warn","ts":1736316461.5836473,"logger":"lifecycle.manager","msg":"Failed to start the extension","error":"invalid configuration: exporters::otlp: address ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}: missing port in address"}
{"level":"info","ts":1736316461.5844429,"msg":"done","error":"invalid configuration: exporters::otlp: address ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}: missing port in address; request failed with status 202 Accepted","errorCauses":[{"error":"invalid configuration: exporters::otlp: address ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}: missing port in address"},{"error":"request failed with status 202 Accepted"}]}
EXTENSION Name: collector State: InitError Events: [INVOKE, SHUTDOWN]
INIT_REPORT Init Duration: 283.91 ms Phase: init Status: error Error Type: Extension.InitError
{"level":"info","ts":1736316462.3791473,"msg":"Launching OpenTelemetry Lambda extension","version":"v0.115.0"}
{"level":"info","ts":1736316462.4020228,"logger":"telemetryAPI.Listener","msg":"Listening for requests","address":"sandbox.localdomain:53612"}
{"level":"info","ts":1736316462.4021611,"logger":"telemetryAPI.Client","msg":"Subscribing","baseURL":"http://127.0.0.1:9001/2022-07-01/telemetry"}
TELEMETRY Name: collector State: Already subscribed Types: [Platform]
{"level":"info","ts":1736316462.4196353,"logger":"telemetryAPI.Client","msg":"Subscription success","response":"\"AlreadySubscribed\""}
{"level":"info","ts":1736316462.4198246,"logger":"NewCollector","msg":"Using config URI from environment variable","uri":"/var/task/collector.yaml"}
{"level":"warn","ts":1736316462.4785774,"logger":"lifecycle.manager","msg":"Failed to start the extension","error":"unable to start, otelcol state is Closed"}
{"level":"info","ts":1736316462.4791973,"msg":"done","error":"unable to start, otelcol state is Closed; request failed with status 202 Accepted","errorCauses":[{"error":"unable to start, otelcol state is Closed"},{"error":"request failed with status 202 Accepted"}]}
EXTENSION Name: collector State: InitError Events: [INVOKE, SHUTDOWN]
INIT_REPORT Init Duration: 879.88 ms Phase: invoke Status: error Error Type: Extension.InitError
START RequestId: 3c230445-79e0-4fc8-b9c1-5359acc07283 Version: $LATEST
RequestId: 3c230445-79e0-4fc8-b9c1-5359acc07283 Error: exit code 0 Extension.InitError
END RequestId: 3c230445-79e0-4fc8-b9c1-5359acc07283
REPORT RequestId: 3c230445-79e0-4fc8-b9c1-5359acc07283 Duration: 881.54 ms Billed Duration: 882 ms Memory Size: 512 MB Max Memory Used: 42 MB
```

From the above, it appears to be initialising the layer, but then deciding that the configuration hasn't specified the port number (although you can see the port number specified in my `template.yaml`, which should then be passed through in its environment variable to the `collector.yaml`). Having failed once, it tries a second time, this time because collector has already shut down. Finally, AWS gives up in despair and doesn't bother trying again, just reporting the error back.

Given that the first error message implies that the `exporters:oltp:endpoint` parameter is not being set properly from the environment variable set in `template.yaml`, I tried replacing the `${NEW_RELIC_OPENTELEMETRY_ENDPOINT}` variable with the hard-coded value (`
otlp.nr-data.net:4317`) and the integration ran correctly. Interestingly, the `${NEW_RELIC_LICENSE_KEY}` is obviously being set correctly in `collector.yaml` as I am not getting any authentication errors when attempting to submit traces.

Any thoughts as to why the environment variable `NEW_RELIC_OPENTELEMETRY_ENDPOINT` set in `template.yaml` is not being set correctly in `collector.yaml` when `NEW_RELIC_LICENSE_KEY` is?

**What version of collector/language SDK version did you use?**

Version: arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-collector-amd64-ver-0-115-0:2

**What language layer did you use?**

Config: `.NET`

**Comment by serkan-ozal** [comment]
Hi @davidkeaveny, 

It seems that you are using AWS ADOT layer. 
Are you sure that you run `sam build` after you have added `NEW_RELIC_OPENTELEMETRY_ENDPOINT` and before `sam deploy` to deploy the template? 
Can you also check that `NEW_RELIC_OPENTELEMETRY_ENDPOINT` env var is really exist in the Lambda function you deployed when you open the AWS Lambda console?

**Comment by mmesdag-tp** [comment]
I'm seeing the same issue after updating the layer version from `aws-otel-collector-arm64-ver-0-102-1:1` to `aws-otel-collector-arm64-ver-0-115-0:2`. I reached out to AWS enterprise support, they said that the new layer version is only compatible with the dotnet core 3.1 and dotnet 6 runtimes, which sounds crazy to me. 

I tried updating my config to hardcode the exporter url, which fixes the extension crashing on startup, but doesn't actually result in telemetry being sent where it's supposed to go. 

Doesn't crash but also doesn't send telemetry:
```yml
exporters:
  otlp/newrelic:
    endpoint: otlp.nr-data.net:4317
```

Crashes:
collector.yaml
```yml
exporters:
  otlp/newrelic:
    endpoint: ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}
```
template.yaml
```yml
    Environment:
      Variables:
        NEW_RELIC_OPENTELEMETRY_ENDPOINT: otlp.nr-data.net:4317
```

**Comment by Aneurysm9** [comment]
Can you try using `${env:NEW_RELIC_OPENTELEMETRY_ENDPOINT}`?  The collector extension's [configuration resolver settings](https://github.com/open-telemetry/opentelemetry-lambda/blob/6a8b279f6f16d3747f2ca509ab53447f763801f1/collector/internal/collector/collector.go#L74-L84) do not specify a default scheme, so all configuration substitutions require an explicit scheme.  The error message:

> "invalid configuration: exporters::otlp: address ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}: missing port in address"

indicates that `${NEW_RELIC_OPENTELEMETRY_ENDPOINT}` is the string passed [here](https://github.com/open-telemetry/opentelemetry-collector/blob/da5b68ad43e305566a956b8693213cd3209ab269/exporter/otlpexporter/config.go#L41) to `net.SplitHostPort()` which returned [this error](https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/net/ipsock.go;l=167).

**Comment by davidkeaveny** [comment]
Hi @serkan-ozal , we don't use the SAM CLI to deploy - we use GitHub Actions to build and push to Octopus Deploy - more specifically, the code gets deployed to S3 in a .zip file, while the SAM template gets pushed to Octopus itself, which then does the actual deployment work. Octopus looks after the environment-specific configurations (database connection strings etc) and sets them at deploy-time.

**Comment by davidkeaveny** [comment]
@Aneurysm9 I tried your suggested fix (specifying the explicit scheme in `collector.yaml`) and that seems to have done the trick - the lambda function does not immediately error on initialisation when I test the lambda.

Unfortunately, it has exposed another issue - in the CloudWatch logs, I can now see the following:

```
{
  "level": "error",
  "ts": 1737531158.416912,
  "caller": "internal/base_exporter.go:139",
  "msg": "Exporting failed. Rejecting data. Try enabling sending_queue to survive temporary failures.",
  "kind": "exporter",
  "data_type": "traces",
  "name": "otlp",
  "error": "not retryable error: Permanent error: rpc error: code = Internal desc = server closed the stream without sending trailers",
  "rejected_items": 3,
  "stacktrace": "go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send\n\tgo.opentelemetry.io/collector/exporter@v0.115.0/exporterhelper/internal/base_exporter.go:139\ngo.opentelemetry.io/collector/exporter/exporterhelper.NewTracesRequest.func1\n\tgo.opentelemetry.io/collector/exporter@v0.115.0/exporterhelper/traces.go:135\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.22.0/traces.go:26\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.22.0/traces.go:26\ngo.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace.(*Receiver).Export\n\tgo.opentelemetry.io/collector/receiver/otlpreceiver@v0.115.0/internal/trace/otlp.go:42\ngo.opentelemetry.io/collector/pdata/ptrace/ptraceotlp.rawTracesServer.Export\n\tgo.opentelemetry.io/collector/pdata@v1.22.0/ptrace/ptraceotlp/grpc.go:89\ngo.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler.func1\n\tgo.opentelemetry.io/collector/pdata@v1.22.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:310\ngo.opentelemetry.io/collector/config/configgrpc.(*ServerConfig).getGrpcServerOptions.enhanceWithClientInformation.func9\n\tgo.opentelemetry.io/collector/config/configgrpc@v0.115.0/configgrpc.go:523\ngo.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler\n\tgo.opentelemetry.io/collector/pdata@v1.22.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:312\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\tgoogle.golang.org/grpc@v1.68.1/server.go:1394\ngoogle.golang.org/grpc.(*Server).handleStream\n\tgoogle.golang.org/grpc@v1.68.1/server.go:1805\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\tgoogle.golang.org/grpc@v1.68.1/server.go:1029"
}
```

**UPDATE**: of course, if the `${NEW_RELIC_OPENTELEMETRY_ENDPOINT}` needs the `env:` scheme provided then the `${NEW_RELIC_LICENSE_KEY}` variable is definitely going to need the same change 🤦 So now my `collector.yaml` looks like this:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: ${env:NEW_RELIC_OPENTELEMETRY_ENDPOINT}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
```

and there are no errors in CloudWatch.
