### ISSUE TITLE
Getting "the grpc server returns error Unknown error" in cloudwatch

### ISSUE THREAD

**Issue by sarmst22** [open-telemetry/opentelemetry-lambda-extension#171]
I'm working with the open-telemetry rust otlp pipeline in a AWS lambda and I've started running across an error that appears to be preventing my traces from propagating to X-Ray:
```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error Unknown error
```
Below is my current collector.yaml configuration; is there something incorrect about my configuration setup that's causing this issue?  Or is this a bug?

```
#collector.yaml in the root directory
#Set an environemnt variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/<path/<to>/<file>'

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  awsxray:
  otlp:
    endpoint: 0.0.0.0:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, awsxray, otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging]
```

**Comment by anuraaga** [comment]
Hi @sarmst22 - You probably meant to remove the OTLP exporter in this pipeline (but keep the receiver). Currently it is pointing to 0.0.0.0, which is not a valid endpoint for exporting (it is an IP range that can be set for receiving). If you don't have a concrete address for that setting, it probably means you don't need the exporter enabled.

**Comment by sarmst22** [comment]
Hi @anuraaga thanks so much; I gave your recommendation a shot and I still get the same errors. 
```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error Unknown error
```
Here's my config setup now:
```
#collector.yaml in the root directory
#Set an environemnt variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/<path/<to>/<file>'

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


exporters:
  logging:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      exporters: [logging]
```

Any other tips for the source of this problem?
