### ISSUE TITLE
Trying to Bind to Random Port and Failing

### ISSUE THREAD

**Issue by swcloudgenie** [open-telemetry/opentelemetry-lambda-extension#1740]
**Describe the bug**
During some cold start invocations, we see this error coming from the collector layer:

```json
{
    "level": "error",
    "ts": 1741771824.3853145,
    "logger": "telemetryAPI.Listener",
    "msg": "Unexpected stop on HTTP Server",
    "error": "listen tcp 169.254.100.6:53612: bind: address already in use"
}
```

Our configuration is as follows:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
exporters:
  otlp/groundcover:
    endpoint: ****REDACTED****
    headers:
      apikey: ****REDACTED****
processors:
  batch:
    send_batch_size: 20
  decouple:
    max_queue_size: 100
  resource/groundcover:
    attributes:
      - action: insert
        key: env_name
        value: prod
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - resource/groundcover
        - batch
        - decouple
      exporters:
        - otlp/groundcover
    metrics:
      receivers:
        - otlp
      processors:
        - resource/groundcover
        - batch
        - decouple
      exporters:
        - otlp/groundcover
    logs:
      receivers:
        - otlp
      processors:
        - resource/groundcover
        - batch
        - decouple
      exporters:
        - otlp/groundcover
```

**Steps to reproduce**
This seems to happen intermittently, maybe once or twice a day for high volume functions.

**What did you expect to see?**
We would not expect to bind to 169.254.100.6:53612 since that IP/Port does not exist in our configuration.

**What did you see instead?**
Collector tried to bind to 169.254.100.6:53612 and failed

**What version of collector/language SDK version did you use?**
Version: 
arn:aws:lambda:us-east-2:184161586896:layer:opentelemetry-collector-arm64-0_12_0:1

**What language layer did you use?**
Config: NodeJS

**Additional context**
Also use the NodeJS layer: arn:aws:lambda:us-east-2:184161586896:layer:opentelemetry-nodejs-0_11_0:1
