### ISSUE TITLE
Failed to start the extension: unable to start, otelcol state is 3

### ISSUE THREAD

**Issue by gr4vitonn** [open-telemetry/opentelemetry-lambda-extension#245]
Hello there.

I got the following error: "Failed to start the extension: unable to start, otelcol state is 3".

I've tried to figure it out, but I found nothing useful here or on stackoverflow.

I have a java lambda what I'm trying to integrate with Honeycomb.

Please let me know if you need additional information. What I'm looking for here is a direction to be able to solve the problem.

**Comment by stephenhong** [comment]
Hello @gr4vitonn , I'm experiencing the same issue. Were you able to resolve this?

**Comment by iulspop** [comment]
Encountered same problem too :(

My `collector.yaml` config:
```
exporters:
  otlp/traces:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/traces]
```

**Comment by iulspop** [comment]
I changed my `collector.yaml` configuration and that fixed it!
```
receivers:
  otlp:
    protocols:
      http:
      grpc:
exporters:
  otlp/traces:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/traces]
```
I was misreading the docs [here](https://aws-otel.github.io/docs/components/otlp-exporter#honeycomb:~:text=you%27re%20sending%20them-,Example,-To%20send%20trace)
