### ISSUE TITLE
Collector Crashes When Using Attributes Processor

### ISSUE THREAD

**Issue by kolanos** [open-telemetry/opentelemetry-lambda-extension#250]
## Overview

I am attempting to use the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) in a custom collector config. However when I do so the collector crashes.

## Config

Config looks like this:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  awsxray:

processors:
  attributes:
    actions:
      - key: opentelemetry.trace.id
        action: upsert
        from_attribute: trace.id
      - key: opentelemetry.span.id
        action: upsert
        from_attribute: span.id

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
```

## Logs

```
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.633000 2022/06/15 22:22:34 [collector] Launching OpenTelemetry Lambda extension, version:  v0.1.0
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.633000 2022/06/15 22:22:34 Using config file at path /var/task/collector.yaml
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.689000 2022/06/15 22:22:34 Failed to start the extension: unable to start, otelcol state is 3
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.690000 EXTENSION	Name: collector	State: Started	Events: []
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.691000 END RequestId: 2efc3e43-8004-4838-bc3e-6ca122928af2
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.691000 REPORT RequestId: 2efc3e43-8004-4838-bc3e-6ca122928af2	Duration: 708.22 ms	Billed Duration: 709 ms	Memory Size: 512 MBMax Memory Used: 39 MB	
XRAY TraceId: 1-62aa5ba8-0034478a42fb98a10192a009	SegmentId: 3f3386065445ef0d	Sampled: true	
2022/06/15/[$LATEST]f543f4d6a4944c9ab020da67e69224ed 2022-06-15T22:22:34.691000 RequestId: 2efc3e43-8004-4838-bc3e-6ca122928af2 Error: exit status 1
Extension.Crash
```

## Version

* `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-java-agent-amd64-ver-1-14-0:2`

**Comment by kolanos** [comment]
When I remove the processor from the pipeline entirely, it still crashes. So appears to be an issue loading the processor?

This still results in a crash:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  awsxray:

processors:
  attributes:
    actions:
      - key: opentelemetry.trace.id
        action: upsert
        from_attribute: trace.id
      - key: opentelemetry.span.id
        action: upsert
        from_attribute: span.id

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
```
