### ISSUE TITLE
Service map with Elastic APM

### ISSUE THREAD

**Issue by mauriciocm9** [open-telemetry/opentelemetry-lambda-extension#449]
Currently I've 2 lambdas that are connected with a SNS trigger. Traces from both services are arriving correctly to elastic apm using the same trace id. However services map isn't showing the connection between these 2 lambdas. After debugging the spans from the second lambda, it seems that the parent id is pointing to a X-ray subsegment generated by the lambda runtime and unreachable from the extension. After reviewing the repo, it seems that the telemetryAPI could extract these missing X-ray spans but after enabling this feature it doesn't seem to post the missing traces to elastic. This is the yml I'm using:

```yaml
# Copy collector.yaml in the root directory
# Set an environment variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/collector.yaml'
receivers:
  telemetryapi:
  otlp:
    protocols:
      grpc:
      http:

processors:
    coldstart:
 
exporters:
  logging:
    loglevel: debug
  otlp/elastic:
    # APM server https endpoint without https://
    endpoint: "${APM_SERVER_URL}"
    headers:
      # APM Server secret token
      Authorization: "Bearer ${APM_SERVER_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
```

I build the extension from master and apparently the telemetry API seems to be working but not sending the traces:
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/28741504/215350833-5dad8a0a-aac9-43b3-8399-7d861da7025b.png">
