### ISSUE TITLE
s3:// style configuration URI does not work for collector configuration

### ISSUE THREAD

**Issue by sasha-wing** [open-telemetry/opentelemetry-lambda-extension#515]
**Describe the bug**
Hello, I followed the [configuration guide](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/README.md#configuration)
and tried to configure my otel collector with a configuration located in an S3 bucket.

According to the guide, I should be able to use a URI with the `s3:` schema  but when I do it I get the error:
```yaml
{
    "level": "fatal",
    "ts": 1676898184.1288683,
    "logger": "NewCollector",
    "msg": "error creating config provider",
    "error": "unsupported scheme on URI \"s3://mybucket/mykey\""
}
```
I have given my lambda role permissions to the resource

**Steps to reproduce** 
Create a lambda with an s3 style uri configuration 

**What did you expect to see?**
It working

**What did you see instead?**
error

**What version of collector/language SDK version did you use?**
OpenTelemetry Lambda extension v0.25.0

**What language layer did you use?**
python and go
