### ISSUE TITLE
Exporter endpoint doesn't send traces

### ISSUE THREAD

**Issue by jose-mf** [open-telemetry/opentelemetry-lambda-extension#647]
**Describe the bug**
Are not sent any trace to the exporter endpoint when lambda receives many requests per second but in the case of sending logs all works as expected.

**Steps to reproduce**
The application I'm using for this test is based on ab Api Gateway integrated with a Lambda (store a record in dynamodb table). It's a simple API endpoint to create a resource in the database.

If I create an isolated request, all work as expected, and logs and traces are shown in New Relic.

The problem was when I tried to use AWS Load Testing Tool to generate some Requests per second, and in this case, logs arrives at New Relic but nothing about traces.

**What did you expect to see?**
All the traces in New Relic (exporter endpoint)

**What did you see instead?**
No traces are shown in New Relic.

**What version of collector/language SDK version did you use?**
Version: (`v0.70`)

**What language layer did you use?**
Config: (`dotnet`)
The collector configuration is shown below:
``` yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ${NEW_RELIC_OPENTELEMETRY_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging,otlp]
    logs:
      receivers: [otlp]
      exporters: [logging,otlp]
```

**Additional context**
