### ISSUE TITLE
Lambda Extension failing to start with "unable to start, otelcol state is 3; request failed with status 403 Forbidden"

### ISSUE THREAD

**Issue by its-felix** [open-telemetry/opentelemetry-lambda-extension#750]
**Describe the bug**
The extension is failing to start with the following error message:
```
unable to start, otelcol state is 3; request failed with status 403 Forbidden
```

The full CloudWatch Logs for a failing invocation:

---
| @timestamp | @message |
| --- | --- |
| 2023-06-11 04:03:30.102 | RequestId: b3e49638-9b9d-4f61-8ff9-c00b762c6453 Error: exit code 0 Extension.Crash |
| 2023-06-11 04:03:30.102 | END RequestId: b3e49638-9b9d-4f61-8ff9-c00b762c6453 |
| 2023-06-11 04:03:30.102 | REPORT RequestId: b3e49638-9b9d-4f61-8ff9-c00b762c6453 Duration: 1531.32 ms Billed Duration: 1532 ms Memory Size: 256 MB Max Memory Used: 46 MB  XRAY TraceId: 1-6485478f-6f0354620c008ee126dc33e2 SegmentId: 7a629c482beece2b Sampled: true |
| 2023-06-11 04:03:30.083 | START RequestId: b3e49638-9b9d-4f61-8ff9-c00b762c6453 Version: $LATEST |
| 2023-06-11 04:03:30.082 | EXTENSION Name: layer State: Ready Events: [INVOKE, SHUTDOWN] |
| 2023-06-11 04:03:30.081 | {"level":"info","ts":1686456210.0816703,"msg":"done","error":"failed to get config: cannot resolve the configuration: cannot retrieve the configuration: unable to read the file file:/var/task/collector.yaml: open /var/task/collector.yaml: no such file or directory; request failed with status 403 Forbidden","errorCauses":[{"error":"failed to get config: cannot resolve the configuration: cannot retrieve the configuration: unable to read the file file:/var/task/collector.yaml: open /var/task/collector.yaml: no such file or directory"},{"error":"request failed with status 403 Forbidden"}]} |
| 2023-06-11 04:03:30.062 | {"level":"info","ts":1686456210.0617409,"logger":"telemetryAPI.Client","msg":"Subscription success","response":"\"AlreadySubscribed\""} |
| 2023-06-11 04:03:30.062 | {"level":"info","ts":1686456210.0618398,"logger":"NewCollector","msg":"Using config URI from environment","uri":"/var/task/collector.yaml"} |
| 2023-06-11 04:03:30.062 | {"level":"warn","ts":1686456210.062717,"logger":"lifecycle.manager","msg":"Failed to start the extension","error":"failed to get config: cannot resolve the configuration: cannot retrieve the configuration: unable to read the file file:/var/task/collector.yaml: open /var/task/collector.yaml: no such file or directory"} |
| 2023-06-11 04:03:30.042 | TELEMETRY Name: layer State: Already subscribed Types: [Platform] |
| 2023-06-11 04:03:30.041 | {"level":"info","ts":1686456210.0413923,"logger":"telemetryAPI.Listener","msg":"Listening for requests","address":"sandbox:53612"} |
| 2023-06-11 04:03:30.041 | {"level":"info","ts":1686456210.0415072,"logger":"telemetryAPI.Client","msg":"Subscribing","baseURL":"http://127.0.0.1:9001/2022-07-01/telemetry"} |
| 2023-06-11 04:03:29.984 | {"level":"info","ts":1686456209.9841244,"msg":"Launching OpenTelemetry Lambda extension","version":"latest"} |
| 2023-06-11 04:03:28.432 | EXTENSION Name: layer State: Ready Events: [INVOKE, SHUTDOWN] |
| 2023-06-11 04:03:28.430 | {"level":"info","ts":1686456208.430745,"msg":"done","error":"unable to start, otelcol state is 3; request failed with status 403 Forbidden","errorCauses":[{"error":"unable to start, otelcol state is 3"},{"error":"request failed with status 403 Forbidden"}]} |
| 2023-06-11 04:03:28.429 | {"level":"info","ts":1686456208.427401,"logger":"telemetryAPI.Client","msg":"Subscription success","response":"\"OK\""} |
| 2023-06-11 04:03:28.429 | {"level":"info","ts":1686456208.4274786,"logger":"NewCollector","msg":"Using config URI from environment","uri":"/var/task/collector.yaml"} |
| 2023-06-11 04:03:28.429 | {"level":"warn","ts":1686456208.429738,"logger":"lifecycle.manager","msg":"Failed to start the extension","error":"unable to start, otelcol state is 3"} |
| 2023-06-11 04:03:28.426 | TELEMETRY Name: layer State: Subscribed Types: [Platform] |
| 2023-06-11 04:03:28.424 | {"level":"info","ts":1686456208.423885,"logger":"telemetryAPI.Client","msg":"Subscribing","baseURL":"http://127.0.0.1:9001/2022-07-01/telemetry"} |
| 2023-06-11 04:03:28.423 | {"level":"info","ts":1686456208.4232152,"logger":"telemetryAPI.Listener","msg":"Listening for requests","address":"sandbox:53612"} |
| 2023-06-11 04:03:28.417 | {"level":"info","ts":1686456208.4171429,"msg":"Launching OpenTelemetry Lambda extension","version":"latest"} |
| 2023-06-11 04:03:28.190 | INIT_START Runtime Version: go:1.v18 Runtime Version ARN: arn:aws:lambda:eu-central-1::runtime:ccb68acb59818f9df9b10924cc6c83ca6eaf4067f70ba861c0e211b59e8af729 |
---

**Steps to reproduce**
I'm building the layer like seen here https://github.com/gw2auth/gw2auth.com-api/blob/700db95d168f989351b9d6c2089dca784272d625/.github/workflows/build_test_deploy.yml#L69
env:
```
  GO_VERSION: '^1.20.4'
  GOOS: 'linux'
  GOARCH: 'amd64' # keep this in sync with the arch configured in CDK!
  CGO_ENABLED: '0'
  NODE_VERSION: '18'
```
```
          mkdir lambda_layer_bundle
          mkdir lambda_layer_bundle/extensions
          cp otel_collector lambda_layer_bundle/extensions/layer
          cp ../../collector.yaml lambda_layer_bundle/
          chmod +x lambda_layer_bundle/extensions/layer
          (cd lambda_layer_bundle && zip -r ../lambda_layer.zip .)
```

My config looks like this:
```yaml
# https://opentelemetry.io/docs/collector/configuration
# https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/README.md

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  otlp/tempo:
    endpoint: "tempo-eu-west-0.grafana.net:443"
    headers:
      authorization: ${env:OTEL_TEMPO_SECRET}
  prometheusremotewrite:
    endpoint: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
    headers:
      authorization: ${env:OTEL_PROMETHEUS_SECRET}
#  loki:
#    endpoint: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
#    headers:
#      authorization: ${env:OTEL_LOKI_SECRET}

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheusremotewrite]
#    logs:
#      receivers: [otlp]
#      exporters: [logging, loki]
```

And the CDK code to create the layer:
```typescript
        const arch = Architecture.X86_64;
        const otelCollectorLayer = new LayerVersion(this, 'OtelCollectorLayer', {
            removalPolicy: RemovalPolicy.DESTROY,
            code: Code.fromAsset('lambda_layer.zip'),
            compatibleRuntimes: [
                Runtime.GO_1_X,
            ],
            compatibleArchitectures: [
                arch,
            ],
        });
```

**What did you expect to see?**
The extension to successfully start.

**What did you see instead?**
The extension failed to start: `unable to start, otelcol state is 3; request failed with status 403 Forbidden`

**What version of collector/language SDK version did you use?**
https://github.com/open-telemetry/opentelemetry-lambda/tree/c6a7138f19999f2c0adb7b5752b263ad76581647
(I have added this repo as a git submodule to my repo - it's currently pointing at this commit)

**What language layer did you use?**
Go

**Additional context**
