### ISSUE TITLE
Is there a way to forward messages from print, logging.info, logging.warning, etc. to logs pipeline via otlp exporter?

### ISSUE THREAD

**Issue by ok512** [open-telemetry/opentelemetry-lambda-extension#770]
Is there a way to forward messages from print, logging.info, logging.warning, etc. to logs pipeline via otlp exporter?
Not sure, if a different receiver type should be used for logs, tho...
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  logging:
  otlp:

service:
  pipelines:
    logs: 
      receivers: [otlp]
      exporters: [logging, otlp]
```

```
import logging

def lambda_handler(event, context):
    print("Test print")

    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    logger.info("Test info")
    logger.error("Test error")
```
